### ISSUE TITLE
It'll be better if  TOR_PROXY is optional

### ISSUE THREAD

**Issue by yalarmorghulis** [trandoshan-io/crawler#6]
Hi there, 
It will great if TOR_PROXY is optional, coz I can use it to index some website inside intranet network.  In this scenario, a LOGIN_PORXY with cookies will help index some content that's must be login.

**Comment by creekorful** [comment]
Trandoshan is designed to be a dark-web crawler not a clear-web one. If you want to make it work for the clear web you'll need more than just disabling the TOR_PROXY interaction. You'll need to modify the scheduler to remove the ".onion" check that is done

**Comment by creekorful** [comment]
After a bit of thinking, maybe I can add a system property like **ALLOW_CLEAR_WEB_CRAWLING** on the scheduler/crawler project. The property would be false by default but if set to true it will allow that. What do you think ?

**Comment by creekorful** [comment]
After the change I made only crawled is to be modified to allow clear web crawling.

**Comment by yalarmorghulis** [comment]
> After a bit of thinking, maybe I can add a system property like **ALLOW_CLEAR_WEB_CRAWLING** on the crawler. The property would be false by default but if set to true it will allow that. What do you think ?

yep, that'l be great.
